//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseFirstAPP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hangman_DBfirstEntities : DbContext
    {
        public hangman_DBfirstEntities()
            : base("name=hangman_DBfirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<dificulty> dificulties { get; set; }
        public virtual DbSet<word_category> word_category { get; set; }
        public virtual DbSet<word> words { get; set; }
    }
}
