//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseFirstAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class word
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public word()
        {
            this.word_category = new HashSet<word_category>();
        }
    
        public int word_ID { get; set; }
        public string word1 { get; set; }

        public Nullable<int> difficulty_ID { get; set; }
    
        public virtual dificulty dificulty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<word_category> word_category { get; set; }
    }
}
