//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseFirstAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class word_category
    {
        public int word_ID { get; set; }
        public Nullable<int> category_ID { get; set; }
        public int word_category_ID { get; set; }
    
        public virtual category category { get; set; }
        public virtual word word { get; set; }
    }
}
